### ISSUE TITLE
Docker deployment option

### ISSUE THREAD

**Issue by Racum** [olist/work-at-olist#3]
What about to add an option to deploy with Docker? The candidate could provide a `docker-compose.yml` file on the repository root that deploys the system locally with a single command.

**Comment by osantana** [comment]
Nope. We don't use Docker and I don't like it :) (I hate docker to be honest...)

**Comment by Racum** [comment]
I understand your concerns using Docker, I don't think it is mature for production, but for development it gets the **Racum Seal of Approval**! ...specially the version 1.12 with native support for Windows and macOS. Give it a try!

**Comment by osantana** [comment]
We don't need docker when we develop in python with virtualenv. It's solution for a solved problem in Python. I think it adds nothing new to the development process

**Comment by osantana** [comment]
We will suggest "any host" in the new version.
