### ISSUE TITLE
The subscriber name in the Telephone Bill

### ISSUE THREAD

**Issue by Riverfount** [olist/work-at-olist#8]
I'm implementing the work at Olist test, but I have a question, in the second paragraph of item 2 there is the following text:

> 'The telephone bill itself is composed by subscriber name and period attributes and a list of all call records of the period.'

But there is no information about the form that I will receive the subscriber name, how can I implement it?

**Comment by georgeyk** [comment]
Hi @Riverfount 
Thank your for time and effort to apply, we appreciate it beforehand. 

The item1 provide an example about how a subscriber could be identified, but it's open for you to choose how you will do it (and the format as well).

@dvainsencher maybe we should remove the term "name" in the section pointed here to avoid the further doubts.

**Comment by dvainsencher** [comment]
Removed

**Comment by dvainsencher** [comment]
Hi, @Riverfount
I assumed it had been clarified and closed the issue. Is it clear now?

**Comment by Riverfount** [comment]
@georgeyk and @dvainsencher  thank you very much!
