### ISSUE TITLE
About timestamp

### ISSUE THREAD

**Issue by Riverfount** [olist/work-at-olist#9]
Hi guys, I'm here again!

My question, now, is about timestamp. I'm writing tests to create my models, and if I put the naive date I receive a warning about it. The question is: Can I use naive date or I need to use timezone when the user send me the call record?

**Comment by georgeyk** [comment]
@Riverfount 
The test is yours and is up to you to make all the decisions, not only the code will be reviewed, but your choices as well.
In order to code you'll need to think about what justify your choices, there's no wrong or right answers, the test is all open.

**Comment by Riverfount** [comment]
Thank's @georgeyk. That's a great information!
